const Images = {
    backarrow : require('../Image/Frame.png'),
    man : require('../Image/man.png'),
    lock : require('../Image/lock.png'),
    eye : require('../Image/eye.png'),
    eyeoff : require('../Image/eyeoff.png'),
    home : require('../Image/Home.png'),
    homeactive : require('../Image/activehome.png'),
    accountcreation : require('../Image/accountcreation.png'),
    creation:require('../Image/creationactive.png'),
    detail: require('../Image/detail.png'),
    detailactive: require('../Image/detailactive.png'),
    setting: require('../Image/setting.png'),
    drawer: require('../Image/drawer.png'),
    event: require('../Image/event.png'),
    downarrow:require('../Image/downarrow.png'),
    actopass:require('../Image/actopasslogo.png'),
    edit:require('../Image/edit.png'),
    delete:require('../Image/delete.png'),
    selectevent:require('../Image/selectevent.png'),
    comady:require('../Image/comady.png'),
    comd:require('../Image/comd.png'),
    menu:require('../Image/menuboard.png'),
    swip:require('../Image/swip.png'),
    clock:require('../Image/clock.png'),
    location:require('../Image/location.png'),
    cmd:require('../Image/cmd.png'),
    language:require('../Image/language.png'),
    profile:require('../Image/profile.png'),
    settingactive:require('../Image/settingactive.png'),
    settinginactive:require('../Image/settinginactive.png'),
    refer:require('../Image/refer.png'),
    terms:require('../Image/terms.png'),
    activeticket:require('../Image/activeticket.png'),
    inactiveticket:require('../Image/inactiveticket.png'),
    activehistory:require('../Image/activehistory.png'),
    inactivehistory:require('../Image/inactivehistory.png'),
    exa:require('../Image/exa.png'),
    ticket:require('../Image/ticket.png'),
    disc:require('../Image/disc.png'),
    payact:require('../Image/payact.png'),
    help:require('../Image/help.png'),
    otp:require('../Image/otp.png'),
    camera:require('../Image/CameraIcon.png'),
    gallary:require('../Image/gallary.png'),
    success:require('../Image/success.png'),
    editdata:require('../Image/editdata.png'),
    deletedata:require('../Image/deletedata.png'),
    sorry:require('../Image/sorry.png')

}

export default Images;